### ISSUE TITLE
很难理解 kratos 的 layout 到底是映射了什么样的模型

### ISSUE THREAD

**Issue by leeming87v5** [go-kratos/kratos-layout#101]
比如说，为什么 usecase 里面没有用例，反倒 repo 里面有？
所以 repo 才是 usecase ？
到底我写一段代码应该放在 usecase 还是 repo 来实现？

**Comment by deepziyu** [comment]
可以参考 blog
[Go工程化 - Project Layout 最佳实践](https://go-kratos.dev/blog/go-project-layout#%E6%9C%8D%E5%8A%A1%E5%86%85%E9%83%A8%E7%9B%AE%E5%BD%95)
