### ISSUE TITLE
[Question] 配置文件的路径问题

### ISSUE THREAD

**Issue by Nomango** [go-kratos/kratos-layout#104]
默认的configs寻找路径是向上两级，从[这段代码](https://github.com/go-kratos/kratos-layout/blob/8ff9c2694af0e553b2cc31db0f3facb8da71562b/cmd/server/main.go#L30)看出应该是为了配合`kratos run`命令，因为这个命令的work dir是./cmd/server。

但一般项目启动都是在项目根目录下，例如使用`make build`命令生成bin文件后，直接运行bin文件时configs路径查找总是不正确的，也就是kratos run和bin直接启动总有一种会有问题。

是否有必要考虑重新组织一下目录结构？或者应该交给kratos framework来解决，比如修改一下kratos run的work dir？

**Comment by shenqidebaozi** [comment]
kratos run 只是用于本地开发使用

**Comment by Rehtt** [comment]
运行的时候`-conf`指定一下配置文件不就行了

**Comment by Nomango** [comment]
> 运行的时候`-conf`指定一下配置文件不就行了

我的代码强迫症吧，后来看了下kratos run只是简单的go run命令替代品，确实没啥必要care这个东西
