### ISSUE TITLE
maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined

### ISSUE THREAD

**Issue by wjhtime** [go-kratos/kratos-layout#120]
mac os环境，make build之后，启动程序，报这个错

$ bin/server
2022/10/30 22:06:08 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
panic: stat ../../configs: no such file or directory

goroutine 1 [running]:
main.main()
	/Users/xx/go/kratos-layout/cmd/server/main.go:69 +0x677

**Comment by 1jmz** [comment]
> mac os环境，make build之后，启动程序，报这个错
> 
> $ bin/server 2022/10/30 22:06:08 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined panic: stat ../../configs: no such file or directory
> 
> goroutine 1 [running]: main.main() /Users/xx/go/kratos-layout/cmd/server/main.go:69 +0x677

@wjhtime 请问解决了吗，我也遇到了这个问题
