### ISSUE TITLE
-conf 是否支持多个指定文件，而非直接指这目录

### ISSUE THREAD

**Issue by langfengac** [go-kratos/kratos-layout#137]
是否可以类似集成的概念？
base.yaml
config.yaml  > base.yaml
config.dev.yaml > base.yaml

这样我可以不同的环境，使用不同的config，让我的代码闭环发布。
且不用重复的出现相同的配置

**Comment by shenqidebaozi** [comment]
kratos-layout is just a project template that you can modify according to your preferences
