### ISSUE TITLE
layout 优化

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos-layout#66]
@Terry-Mao 
Layout 有几个优化
- [x] Usecase 需要定义在 biz 中；
- [x] Usecase 出入参为 DTO（解决以前模式里，service 传递 Usecase 参数过多的问题），Usecase 负责 DTO 到 DO 转换，反之亦然；
- [x] Usecase 只负责控制编排；
- [x] biz 的 errors 需要定义，可以不依赖 kratos，直接用标准库 errors.New，需要在 Usecase 转换成 kratos errors，需要思考下 mapping 映射
- [ ] 分页规范化
- [ ] field_mask示例
- [ ] 实现 [book](https://github.com/googleapis/googleapis/blob/master/google/example/library/v1/library.proto) 示例

**Comment by tonybase** [comment]
- [ ] 分页规范化
- [ ] field_mask示例
- [ ] 实现 [book](https://github.com/googleapis/googleapis/blob/master/google/example/library/v1/library.proto) 示例
