### ISSUE TITLE
Makefile 缺少了 validate 指令

### ISSUE THREAD

**Issue by Colstuwjx** [go-kratos/kratos-layout#78]
如题，见 [code-generation](https://go-kratos.dev/en/docs/component/middleware/validate#code-generation) 文档部分。

**Comment by haiyux** [comment]
我们不默认支持 validate 命令的makefile了 如果需要的话自己加一下吧 也很方便的 [https://go-kratos.dev/docs/component/middleware/validate/#%E7%94%9F%E6%88%90%E4%BB%A3%E7%A0%81](ttps://go-kratos.dev/docs/component/middleware/validate/#%E7%94%9F%E6%88%90%E4%BB%A3%E7%A0%81)
