### ISSUE TITLE
Use ditroless base image rather than debian slim

### ISSUE THREAD

**Issue by inductor** [go-kratos/kratos-layout#90]
The current base image with debian slim has the following package dependency

https://github.com/go-kratos/kratos-layout/blob/ce6c357221295296cd224502de69bda79c69f438/Dockerfile#L10-L12

It's actually covered by `https://gcr.io/distroless/static-debian11` and even lighter than the slim image.

https://github.com/GoogleContainerTools/distroless/blob/main/gcscache/internal/dpkg/info.go

**Comment by shenqidebaozi** [comment]
Can smaller images provide complete operational support? If yes, can you submit a PR.

**Comment by 117503445** [comment]
<gcr.io/distroless/static-debian11> does not contain the shell . On the one hand this increases security and reduces the size of the image, on the other hand it makes debugging difficult for the user.

My personal preference is to use the distroless image. If this is acceptable to you, I would like to sumbit a PR.
