### ISSUE TITLE
make build 生成的二进制文件名和 Dockerfile CMD 启动名不一样

### ISSUE THREAD

**Issue by yuyicai** [go-kratos/kratos-layout#93]
目前 make build 默认生成二进制文件为项目名称，而 Dockerfile CMD 里面写死了 `./server`  
例如：
- `kratos new helloworld`
- `docker build -t helloworld:v0.1.0 .`
- 那么镜像内的二进制文件名称是`helloworld`

建议：
- make build 时制定生产的二进制文件名为`server`
- 或者在 `kratos new` 时替换 Dockerfile 中的 CMD

获得效果：
- 更丝滑的上手体验

**Comment by tonybase** [comment]
这里主要是个示例，公司内部可以基于自己项目的 scripts 进行构建编译的

**Comment by tonybase** [comment]
这里主要是个示例，公司内部可以基于自己项目的 scripts 进行构建编译的

**Comment by ppusapati** [comment]
`docker run --rm -p 8000:8000 -p 9000:9000 -v configs:/data/conf server`

Any loading of config file example? below is the error if we run the docker image. 

```
INFO msg=watcher's ctx cancel : context canceled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9d55be]

goroutine 1 [running]:
tet/internal/server.NewHTTPServer(0x0, 0xc000132a20, 0xbe37a0, 0xc000374a00, 0x0)
        /src/internal/server/http.go:19 +0xbe
main.wireApp(0x0, 0x0, 0xbe37a0, 0xc000374a00, 0x0, 0xbe37a0, 0xc000374a00, 0xc00006a720)
        /src/cmd/server/wire_gen.go:30 +0x1ca
main.main()
       /src/cmd/server/main.go:74 +0x552
```
